[style]
textColor = "#333333"
primaryColorLight = "#3498db"
primaryColorDark = "#2980b9"
primaryColorText = "#ffffff"

primaryBackground = "#ffffff"
comboBoxColor = "f9f9f9"
secondaryBackground = "#f2f2f2"
hoverColor = "#e5e5e5"
tertiaryBackground = "#d5d5d5"

iconColor = "#6e6e6e"
selectedSideBarTabColor = "#b9b9b9"
tabColorUnselected = "#d3d3d3"
tabColorSelected = "#ffffff"
backgroundColorDisconnected = "#E57373"
backgroundColorServerMessage = "#E1F5FE"
backgroundColorClientMessage = "#FFECB3"
backgroundColorDebugMessage = "#EEEEEE"
backgroundColorServerMessageOdd = "#B3E5FC"
backgroundColorClientMessageOdd = "#FFE082"
backgroundColorDebugMessageOdd = "#E0E0E0"

borderLight = "#c9c9c9"
borderStrong = "#aaaaaa"
borderFocus = "#64B5F6"
shadowFocus = "#90CAF9"
highlightList = "#BBDEFB"
highlight = "#1E88E5"

[plotter]
red = "#F44336"
redLight = "#FFEBEE"
blue = "#3F51B5"
blueLight = "#E8EAF6"
line = "#263238"
lineLight = "#607D8B"
grid = "rgba(0,0,0,0.12)"
gridNumber = "rgba(0,0,0,0.2)"
planetBackground = "#FFFFFF"
plotterBackground = "#E0E0E0"
robot = "#FF9800"
serverRobot = "#BBBBBB"
target = "#AED581"
blocked = "#F44336"
highlight = "#FFC107"
weight = "#666666"

[editor]
keywordColor = "#000080"
directionColor = "#660E7A"
numberColor = "#0000FF"
commentColor = "#808080"
stringColor = "#008000"
selectedLineColor = "#f9f4d9"
errorColor = "#F44336"
