[style]
textColor = "#aeb9b9"
primaryColorLight = "#859900"
primaryColorDark = "#859900"
primaryColorText = "#FFFFFF"

primaryBackground = "#002b36"
comboBoxColor = "002b36"
secondaryBackground = "#073642"
hoverColor = "#073642"
tertiaryBackground = "#586e75"

iconColor = "#6e6e6e"
selectedSideBarTabColor = "#b9b9b9"
tabColorUnselected = "#d3d3d3"
tabColorSelected = "#ffffff"
backgroundColorDisconnected = "#E57373"
backgroundColorServerMessage = "#40C4FF"
backgroundColorClientMessage = "#FFD740"
backgroundColorDebugMessage = "#E0E0E0"

borderLight = "#859900"
borderStrong = "#859900"
borderFocus = "#859900"
shadowFocus = "#657b83"
highlightList = "#073642"
highlight = "#2aa198"

[plotter]
red = "#dc322f"
redLight = "#FFEBEE"
blue = "#268bd2"
blueLight = "#E8EAF6"
line = "#657b83"
lineLight = "#586e75"
grid = "#2c383b"
gridNumber = "#586e75"
background = "#002b36"
robot = "#cb4b16"
target = "#859900"
blocked = "#d33682"
highlight = "#2aa198"
weight = "#657b83"

[editor]
keywordColor = "#b58900"
directionColor = "#dc322f"
numberColor = "#268bd2"
commentColor = "#586e75"
stringColor = "#2aa198"
selectedLineColor = "#073642"
errorColor = "#dc322f"
