stages:
  - build
  - pack
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/


build-backend:
  image: openjdk:11
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew --no-daemon -g .gradle jsBackendSync
  artifacts:
    paths:
      - deploy/server/
    expire_in: 1 hrs
  tags:
    - docker

build-web:
  image: openjdk:11
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew --no-daemon -g .gradle jsFrontendWebSync
  artifacts:
    paths:
      - deploy/distWeb/
    expire_in: 1 hrs
  tags:
    - docker

build-electron:
  image: openjdk:11
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew --no-daemon -g .gradle jsFrontendElectronSync
  artifacts:
    paths:
      - deploy/distElectron/
    expire_in: 1 hrs
  tags:
    - docker

pack-electron:
  image: electronuserland/builder:wine
  stage: pack
  script:
    - cd deploy/electron
    - npm install
    - npx electron-builder build -wl -p never
  needs:
    - job: build-electron
      artifacts: true
  artifacts:
    paths:
      - deploy/electron/dist/
  tags:
    - docker

deploy-backend:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c deploy/server/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/server/
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c deploy/distWeb/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/web/
  needs:
    - job: build-backend
      artifacts: true
    - job: build-web
      artifacts: true
  tags:
    - shell
    - robolab

deploy-electron:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -lptgoDvz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c deploy/electron/dist/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/electron/
  needs:
    - job: pack-electron
      artifacts: true
  tags:
    - shell
    - robolab