image: gradle:jdk14

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build-jvm:
  stage: build
  script: gradle --no-daemon -g .gradle jvmJar
  artifacts:
    paths:
      - build/libs/robolab-jvm.jar
      - build/processedResources/build.ini
    expire_in: 1 hrs
  tags:
    - docker

build-js-client:
  stage: build
  script: gradle --no-daemon -g .gradle jsClientSync
  artifacts:
    paths:
      - web/website
    expire_in: 1 hrs
  tags:
    - docker

build-js-server:
  stage: build
  script: gradle --no-daemon -g .gradle jsServerSync
  artifacts:
    paths:
      - webServer
    expire_in: 1 hrs
  tags:
    - docker

deploy-frontend-develop:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/libs/robolab-jvm.jar deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/develop/frontendJvm/robolab-renderer.jar
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/processedResources/build.ini deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/develop/frontendJvm/build.ini
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/processedResources/build.ini deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/develop/frontend/build.ini
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c web/website/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/develop/frontend/
  only:
    - develop
  environment:
    name: develop/robolab-renderer-frontend
    url: https://robolab.inf.tu-dresden.de/renderer-dev
  needs:
    - job: build-jvm
      artifacts: true
    - job: build-js-client
      artifacts: true
  tags:
    - shell
    - robolab

deploy-backend-develop:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c webServer/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/develop/backend/
  only:
    - develop
  environment:
    name: develop/robolab-renderer-backend
    url: https://robolab.inf.tu-dresden.de/renderer/api
  needs:
    - job: build-js-server
      artifacts: true
  tags:
    - shell
    - robolab

deploy-frontend-stable:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/libs/robolab-jvm.jar deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/frontendJvm/robolab-renderer.jar
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/processedResources/build.ini deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/frontendJvm/build.ini
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c build/processedResources/build.ini deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/frontend/build.ini
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c web/website/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/frontend/
  only:
    - master
  environment:
    name: stable/robolab-renderer-frontend
    url: https://robolab.inf.tu-dresden.de/renderer
  needs:
    - job: build-jvm
      artifacts: true
    - job: build-js-client
      artifacts: true
  tags:
    - shell
    - robolab

deploy-backend-stable:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c webServer/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer/stable/backend/
  only:
    - master
  environment:
    name: stable/robolab-renderer-backend
    url: https://robolab.inf.tu-dresden.de/renderer/api
  needs:
    - job: build-js-server
      artifacts: true
  tags:
    - shell
    - robolab
