stages:
  - build
  - deploy

build-docker-image-stable:
  stage: build

  image: docker:19.03.12
  services:
    - name: docker:19.03.13-dind
      command: [ "--registry-mirror", $CI_REGISTRY ]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/build.Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
  tags:
    - DIND

deploy-docker-image-stable:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:stable
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker pull $IMAGE_TAG
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker-compose -f /home/deploy/web-projects/robolab-docker up -d
  only:
    - master
  tags:
    - robolab
    - shell

build-docker-image-latest:
  stage: build

  image: docker:19.03.12
  services:
    - name: docker:19.03.13-dind
      command: [ "--registry-mirror", $CI_REGISTRY ]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/build.Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - develop
  tags:
    - DIND

deploy-docker-image-latest:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker pull $IMAGE_TAG
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB deploy@robolab.inf.tu-dresden.de docker-compose -f /home/deploy/web-projects/robolab-docker up -d
  only:
    - develop
  tags:
    - robolab
    - shell
