image: gradle:jdk14

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/

build-jvm:
  stage: build
  script: gradle --no-daemon -g .gradle jvmJar
  artifacts:
    paths:
      - build/libs/robolab-jvm.jar
      - build/processedResources/build.ini
  tags:
    - docker

build-js-client:
  stage: build
  script: gradle --no-daemon -g .gradle jsClientSync
  artifacts:
    paths:
      - web/website
  tags:
    - docker

build-js-server:
  stage: build
  script: gradle --no-daemon -g .gradle jsServerSync
  artifacts:
    paths:
      - webServer
  tags:
    - docker

deploy-client:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY
    - rsync -avz --progress -e "ssh -p2201 -o StrictHostKeyChecking=no -i $SSH_KEY" -c build/libs/robolab-jvm.jar ubuntu@robolab.pixix4.com:jvmClient/
    - rsync -avz --progress -e "ssh -p2201 -o StrictHostKeyChecking=no -i $SSH_KEY" -c build/processedResources/build.ini ubuntu@robolab.pixix4.com:jvmClient/
    - rsync -avz --progress -e "ssh -p2201 -o StrictHostKeyChecking=no -i $SSH_KEY" -c web/website/ ubuntu@robolab.pixix4.com:jsClient/website/
    - ssh -p2201 -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@robolab.pixix4.com cp jvmClient/robolab-jvm.jar jvmClient/robolab-renderer.jar
    - ssh -p2201 -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@robolab.pixix4.com cp jvmClient/robolab-jvm.jar jvmClient/robolab-jvmheadless.jar
  only:
    - master
  environment:
    name: pixix4-client
    url: https://robolab.pixix4.com

  needs:
    - job: build-jvm
      artifacts: true
    - job: build-js-client
      artifacts: true
  tags:
    - shell

deploy-server:
  stage: deploy
  script:
    - chmod 0600 $SSH_KEY_ROBOLAB
    - rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i $SSH_KEY_ROBOLAB" -c webServer/ deploy@robolab.inf.tu-dresden.de:web-projects/robolab-renderer-server/
  only:
    - master
  environment:
    name: robolab-server
    url: https://robolab.inf.tu-dresden.de/renderer/api
  needs:
    - job: build-js-server
      artifacts: true
  tags:
    - shell
    - robolab
