version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    container_name: "robolab-renderer"
    environment:
      - PLANETS_DIRECTORY=.
      - PLANETS_DATABASE=redis://redis:6379/4
      - ELECTRON_DIRECTORY=/opt/robolab-render/download
    volumes:
      - ./download:/opt/robolab-render/download
    depends_on:
      - redis
    ports:
      - "3000:8080"
  redis:
    image: redis:latest
    container_name: "robolab-renderer-redis"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
