version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    container_name: "robolab-renderer-backend"
    environment:
      - PLANETS_DIRECTORY=.
      - PLANETS_DATABASE=redis://redis:6379/4
    depends_on:
      - redis
    ports:
      - "3000:8080"
  redis:
    image: redis:latest
    container_name: "robolab-renderer-redis"
    volumes:
      - ./redis-data:/var/lib/redis
