package de.robolab.client.communication

import de.robolab.client.communication.mqtt.MqttClient
import de.robolab.client.utils.TimeoutReference
import de.robolab.client.utils.runAfterTimeoutInterval

fun runDemo(callback: MqttClient.Callback) {
    val messages = generateMessagesForGroup("003", "Piech")
    var index = 0
    var handler: TimeoutReference? = null

    handler = runAfterTimeoutInterval(1000) {
        if (index > messages.lastIndex) {
            handler?.cancel()
            return@runAfterTimeoutInterval
        }

        val (topic, message) = messages[index]
        callback.onMessage(topic, message)
        index += 1
    }
}

fun generateMessagesForGroup(groupName: String, planetName: String): List<Pair<String, String>> {
    return listOf(
            "explorer/$groupName" to """{"from":"client","type":"ready"}""",
            "explorer/$groupName" to """{"from":"server","type":"planet","payload":{"planetName":"$planetName","startX":300,"startY":300,"startOrientation":0}}""",
            "controller/$groupName" to """{"from":"debug","type":"notice","payload":{"planetName":"$planetName","startX":300,"startY":300,"message":"firstBluePoint"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":300,"startY":301,"startDirection":90,"endX":300,"endY":301, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":300,"startY":301,"startDirection":90,"endX":300,"endY":301, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":301,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":300,"endY":301,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":300,"startDirection":180,"endX":299,"endY":300,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":300,"startDirection":180,"endX":299,"endY":300, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":300,"startDirection":180,"endX":299,"endY":300, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":180,"endX":299,"endY":300, "endDirection":270,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":180,"endX":299,"endY":300, "endDirection":270,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":299,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":299,"targetY":307}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":299,"targetY":307}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":302,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":300,"endY":302,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":304,"startDirection":90,"endX":300,"endY":305, "endDirection":270,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":304,"startDirection":90,"endX":300,"endY":305, "endDirection":270,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":303,"startDirection":270,"endX":299,"endY":303, "endDirection":270,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":299,"startY":303,"startDirection":270,"endX":299,"endY":303, "endDirection":270,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":303,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":303,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":304,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":304,"startDirection":0,"endX":299,"endY":304,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":304,"startDirection":0,"endX":299,"endY":305, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":304,"startDirection":0,"endX":299,"endY":305, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":0,"endX":299,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":0,"endX":299,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":305,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":305,"startDirection":0,"endX":299,"endY":305,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":180,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":180,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":306,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":306,"startDirection":270,"endX":299,"endY":306,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":306,"startDirection":270,"endX":298,"endY":305, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":306,"startDirection":270,"endX":298,"endY":305, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":270,"endX":298,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":270,"endX":298,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":305,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 90}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":305,"startDirection":90,"endX":298,"endY":305,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":298,"startY":305,"startDirection":90,"endX":299,"endY":305, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":298,"startY":305,"startDirection":90,"endX":299,"endY":305, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":90,"endX":299,"endY":305, "endDirection":270,"pathStatus":"free","pathWeight":7}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":90,"endX":299,"endY":305, "endDirection":270,"pathStatus":"free","pathWeight":7}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":305,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":305,"startDirection":90,"endX":299,"endY":305,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":299,\"startY\":305,\"startDirection\":90,\"endX\":299,\"endY\":305,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":299,\"startY\":305,\"startDirection\":90,\"endX\":299,\"endY\":305,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":305,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":305,"startDirection":180,"endX":299,"endY":304,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":305,"startDirection":180,"endX":299,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":305,"startDirection":180,"endX":299,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":304,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}, """,
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}, """,
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":305,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":305,"startDirection":270,"endX":298,"endY":305,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":298,\"startY\":305,\"startDirection\":270,\"endX\":298,\"endY\":305,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":298,\"startY\":305,\"startDirection\":270,\"endX\":298,\"endY\":305,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":305,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":306,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":306,"startDirection":0,"endX":299,"endY":306,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":299,\"startY\":306,\"startDirection\":0,\"endX\":299,\"endY\":306,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":299,\"startY\":306,\"startDirection\":0,\"endX\":299,\"endY\":306,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":306,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":299,"endY":306,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":2}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":2}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":306,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":306,"startDirection":0,"endX":300,"endY":306,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":306,\"startDirection\":0,\"endX\":300,\"endY\":306,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":306,\"startDirection\":0,\"endX\":300,\"endY\":306,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":306,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":306,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":305,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":305,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":0,"endX":298,"endY":302, "endDirection":180,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":0,"endX":298,"endY":302, "endDirection":180,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":298,"targetY":300}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":298,"targetY":300}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":304,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathSelect","payload":{"startDirection": 180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":304,"startDirection":180,"endX":300,"endY":304,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":180,"endX":300,"endY":304, "endDirection":180,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":180,"endX":300,"endY":304, "endDirection":180,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":304,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":305,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304, "endDirection":90,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304, "endDirection":90,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":304,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":303,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":0,"endX":298,"endY":302, "endDirection":180,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":0,"endX":298,"endY":302, "endDirection":180,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":303,"startDirection":90,"endX":297,"endY":303, "endDirection":90,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":303,"startDirection":90,"endX":297,"endY":303, "endDirection":90,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":302,"startDirection":270,"endX":297,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":302,"startDirection":270,"endX":297,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":303,"startDirection":0,"endX":297,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":303,"startDirection":0,"endX":297,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":304,"startDirection":90,"endX":297,"endY":304, "endDirection":90,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":304,"startDirection":90,"endX":297,"endY":304, "endDirection":90,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":304,"startDirection":270,"endX":297,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":304,"startDirection":270,"endX":297,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":298,"targetY":307}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":298,"targetY":307}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":302,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":302,"startDirection":0,"endX":298,"endY":302,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":0,"endX":298,"endY":302, "endDirection":0,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":0,"endX":298,"endY":302, "endDirection":0,"pathStatus":"blocked","pathWeight":-1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":302,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":302,"startDirection":90,"endX":299,"endY":303,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":90,"endX":299,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":90,"endX":299,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":303,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":303,"startDirection":90,"endX":300,"endY":302,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":90,"endX":300,"endY":302, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":90,"endX":300,"endY":302, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":302,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":302,"startDirection":180,"endX":300,"endY":302,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":302,\"startDirection\":180,\"endX\":300,\"endY\":302,\"endDirection\":180,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":302,\"startDirection\":180,\"endX\":300,\"endY\":302,\"endDirection\":180,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":302,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":302,"startDirection":90,"endX":300,"endY":302,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":302,\"startDirection\":90,\"endX\":300,\"endY\":302,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":302,\"startDirection\":90,\"endX\":300,\"endY\":302,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":302,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":302,"startDirection":270,"endX":299,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":270,"endX":299,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":270,"endX":299,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":300,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":300,"startDirection":90,"endX":300,"endY":301,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":90,"endX":300,"endY":301, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":90,"endX":300,"endY":301, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":301,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":301,"startDirection":180,"endX":300,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":180,"endX":300,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":180,"endX":300,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":300,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":300,"startDirection":90,"endX":300,"endY":300,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":300,\"startDirection\":90,\"endX\":300,\"endY\":300,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":300,\"startDirection\":90,\"endX\":300,\"endY\":300,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":300,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":300,"startDirection":270,"endX":300,"endY":300,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":300,\"startDirection\":270,\"endX\":300,\"endY\":300,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":300,\"startDirection\":270,\"endX\":300,\"endY\":300,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":300,"startDirection":0,"endX":300,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":301,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":301,"startDirection":270,"endX":299,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":300,"startDirection":0,"endX":300,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":302,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":302,"startDirection":0,"endX":299,"endY":303, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":303,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":0,"endX":299,"endY":304, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":304,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":270,"endX":298,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":305,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":305,"startDirection":0,"endX":299,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":306,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":2}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":306,"startDirection":90,"endX":300,"endY":306, "endDirection":270,"pathStatus":"free","pathWeight":2}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":306,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":306,"startDirection":90,"endX":300,"endY":306,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":306,\"startDirection\":90,\"endX\":300,\"endY\":306,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":306,\"startDirection\":90,\"endX\":300,\"endY\":306,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":306,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":306,"startDirection":180,"endX":300,"endY":305, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":305,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":305,"startDirection":90,"endX":300,"endY":305,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":305,\"startDirection\":90,\"endX\":300,\"endY\":305,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":305,\"startDirection\":90,\"endX\":300,\"endY\":305,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":305,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":180,"endX":300,"endY":304, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":304,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":304,"startDirection":90,"endX":300,"endY":304,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":304,\"startDirection\":90,\"endX\":300,\"endY\":304,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":304,\"startDirection\":90,\"endX\":300,\"endY\":304,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":304,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":304,"startDirection":270,"endX":300,"endY":304,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":304,\"startDirection\":270,\"endX\":300,\"endY\":304,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":300,\"startY\":304,\"startDirection\":270,\"endX\":300,\"endY\":304,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":304,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":304,"startDirection":0,"endX":300,"endY":305, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":300,"startY":305,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304, "endDirection":90,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":300,"startY":305,"startDirection":270,"endX":299,"endY":304, "endDirection":90,"pathStatus":"free","pathWeight":4}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":304,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":304,"startDirection":180,"endX":299,"endY":303, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":299,"startY":303,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":299,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":90,"pathStatus":"free","pathWeight":45}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":302,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":302,"startDirection":270,"endX":297,"endY":303,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":270,"endX":297,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":270,"endX":297,"endY":303, "endDirection":180,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":303,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":303,"startDirection":270,"endX":297,"endY":303,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":303,\"startDirection\":270,\"endX\":297,\"endY\":303,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":303,\"startDirection\":270,\"endX\":297,\"endY\":303,\"endDirection\":270,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":303,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":303,"startDirection":180,"endX":298,"endY":302,"endDirection":270,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":303,"startDirection":180,"endX":298,"endY":302, "endDirection":270,"pathStatus":"free","pathWeight":50}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":302,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":302,"startDirection":180,"endX":298,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":180,"endX":298,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":302,"startDirection":180,"endX":298,"endY":300, "endDirection":0,"pathStatus":"free","pathWeight":99}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":270,"endX":297,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":298,"startY":300,"startDirection":270,"endX":297,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":300,"startDirection":270,"endX":296,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":300,"startDirection":270,"endX":296,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":300,"startDirection":0,"endX":297,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":6}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":297,"startY":300,"startDirection":0,"endX":297,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":6}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":296,"startY":301,"startDirection":90,"endX":297,"endY":301, "endDirection":270,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"pathUnveiled","payload":{"startX":296,"startY":301,"startDirection":90,"endX":297,"endY":301, "endDirection":270,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":296,"targetY":300}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":296,"targetY":300}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":298,"startY":300,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":298,"startY":300,"startDirection":270,"endX":297,"endY":300,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":300,"startDirection":270,"endX":297,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":298,"startY":300,"startDirection":270,"endX":297,"endY":300, "endDirection":90,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":296,"targetY":301}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":296,"targetY":301}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":300,"startDirection":0,"endX":297,"endY":301,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":300,"startDirection":0,"endX":297,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":6}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":300,"startDirection":0,"endX":297,"endY":301, "endDirection":180,"pathStatus":"free","pathWeight":6}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":294,"targetY":301}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":294,"targetY":301}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":301,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":301,"startDirection":0,"endX":297,"endY":301,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":301,\"startDirection\":0,\"endX\":297,\"endY\":301,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":301,\"startDirection\":0,\"endX\":297,\"endY\":301,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":301,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":301,"startDirection":90,"endX":297,"endY":301,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":301,\"startDirection\":90,\"endX\":297,\"endY\":301,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":297,\"startY\":301,\"startDirection\":90,\"endX\":297,\"endY\":301,\"endDirection\":90,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":297,"startY":301,"startDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":297,"startY":301,"startDirection":270,"endX":296,"endY":301,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":301,"startDirection":270,"endX":296,"endY":301, "endDirection":90,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":297,"startY":301,"startDirection":270,"endX":296,"endY":301, "endDirection":90,"pathStatus":"free","pathWeight":5}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":296,"startY":301,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":296,"startY":301,"startDirection":0,"endX":296,"endY":301,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":296,"startY":301,"startDirection":0,"endX":296,"endY":300, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":296,"startY":301,"startDirection":0,"endX":296,"endY":300, "endDirection":270}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":296,"startY":301,"startDirection":0,"endX":296,"endY":300, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":296,"startY":301,"startDirection":0,"endX":296,"endY":300, "endDirection":270,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":296,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":296,"startY":300,"startDirection":0,"endX":296,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":296,\"startY\":300,\"startDirection\":0,\"endX\":296,\"endY\":300,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":296,\"startY\":300,\"startDirection\":0,\"endX\":296,\"endY\":300,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":296,"startY":300,"startDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":296,"startY":300,"startDirection":180,"endX":296,"endY":300,"endDirection":180,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":296,"startY":300,"startDirection":180,"endX":294,"endY":300, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":296,"startY":300,"startDirection":180,"endX":294,"endY":300, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":296,"startY":300,"startDirection":180,"endX":294,"endY":300, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":296,"startY":300,"startDirection":180,"endX":294,"endY":300, "endDirection":180,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":294,"startY":300,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":294,"startY":300,"startDirection":0,"endX":294,"endY":300,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":294,\"startY\":300,\"startDirection\":0,\"endX\":294,\"endY\":300,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"error","payload":{"message":"path not found","debug":"{\"from\":\"client\",\"type\":\"path\",\"payload\":{\"startX\":294,\"startY\":300,\"startDirection\":0,\"endX\":294,\"endY\":300,\"endDirection\":0,\"pathStatus\":\"free\",\"pathWeight\":null}}"}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":294,"startY":300,"startDirection":90}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":294,"startY":300,"startDirection":90,"endX":294,"endY":300,"endDirection":90,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":294,"startY":300,"startDirection":90,"endX":294,"endY":306, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":294,"startY":300,"startDirection":90,"endX":294,"endY":306, "endDirection":180}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":294,"startY":300,"startDirection":90,"endX":294,"endY":306, "endDirection":180,"pathStatus":"free","pathWeight":76}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":294,"startY":300,"startDirection":90,"endX":294,"endY":306, "endDirection":180,"pathStatus":"free","pathWeight":76}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"pathSelect","payload":{"startX":294,"startY":306,"startDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"client","type":"path","payload":{"startX":294,"startY":306,"startDirection":0,"endX":294,"endY":306,"endDirection":0,"pathStatus":"free","pathWeight":null}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":294,"startY":306,"startDirection":0,"endX":297,"endY":306, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"debug","type":"adjust","payload":{"startX":294,"startY":306,"startDirection":0,"endX":297,"endY":306, "endDirection":0}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":294,"startY":306,"startDirection":0,"endX":297,"endY":306, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"path","payload":{"startX":294,"startY":306,"startDirection":0,"endX":297,"endY":306, "endDirection":0,"pathStatus":"free","pathWeight":1}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":297,"targetY":306}}""",
            "planet/$planetName/$groupName" to """{"from":"server","type":"target","payload":{"targetX":297,"targetY":306}}""",
            "explorer/$groupName" to """{"from":"client","type":"targetReached","payload":{"message":"Target was reached!"}}""",
            "explorer/$groupName" to """{"from":"server","type":"done","payload":{"message":"well done, final target reached - get ready for extraction"}}""",
            "explorer/$groupName" to """{"from":"server","type":"done","payload":{"message":"well done, final target reached - get ready for extraction"}}"""
    )
}
